### ISSUE TITLE
Cannot combine bags 1.12.2

### ISSUE THREAD

**Issue by IamAlathe** [Malorolam/LootBags#111]
In previous versions, you could combine bags to get higher tier bags (4 common make 1 uncommon, and so on).  This does not seem to be a thing in 1.12.2, so I'm wondering if this is intentional or a bug?  The loot recycler gives more than one bag for much of the loot that can be recycled, so I'm actually producing more tier one bags than I can use.  Combining would help with the question of "What do I do with all these white bags?"

Minecraft 1.12.2
Loot Bags 1.12.2-2.5.3b

**Comment by Malorolam** [comment]
It's an intentional fix to a fundamental change to how Minecraft handles recipes now.  Since they're pulled from .json files, having dynamic recipes like in previous versions isn't as feasible as it was before.  The bag tier crafting is now handled in the Lootbags Storage Block.

And the recycler giving more bags than needed was a slight default config bug connected to the changes in the vanilla loot tables, I adjusted the default values so it should be closer to a 1:1 to total bag contents to new bags over a large average.

**Comment by IamAlathe** [comment]
Cool.  Thank you for the explanation.  Now I have a better understanding of the storage block, I didn't realize that's what it was for.  I'll be sure to update when that comes out so I don't flood myself with bags. :)
