### ISSUE TITLE
Drop chance for minecraft 1.12.2 

### ISSUE THREAD

**Issue by zezreli** [Malorolam/LootBags#122]
hey malorolam,
so I'm playing with a few mods including yours, and the main issue i have is that lootbags fills my inventory and stuff like that. i have a lot of mods that affect the drop rate of items. and i would like to be able to lower the drop rate of lootbags so that they don't feel to be to over powered. how do i fix this ?

**Comment by Malorolam** [comment]
I use my own handling system for bag drops, so no other mod should be able to affect them unless it is especially coded to do so.  You can change how often bags can drop one of two ways.
On a bag-by-bag basis, in Lootbags_BagConfig.cfg under each bag there are four fields:
`    $PASSIVESPAWNWEIGHT:50`
`    $PLAYERSPAWNWEIGHT:100`
`    $MOBSPAWNWEIGHT:100`
`    $BOSSSPAWNWEIGHT:200`
these control the weight in each category.  The first three are fairly obvious, the boss field controls anything that is considered a boss by the game, so if a healthbar appears, this is the field that's applied.  Larger integers contribute to a higher relative chance, up to the weighting resolution, which defaults to 1000.  Simply change the numbers to adjust.
The second way is to change the weighting resolution itself in lootbags.cfg, which drops the relative chance for every single bag, so increasing the resolution from 1000 to 2000 means that any bag that has a weight of 100 instead of a 10% chance to drop (roughly), now has a 5% chance to drop.  This does operate relative to the bag weights though, so changes under a couple hundred or over a few tens of thousands don't have much noticeable effect unless you're tweaking the bag weights as well.

Since you're trying to reduce the power level of the mod, I'd also suggest making sure
`B:"Prevent Merging Opened Bags"=true`
and double or triple the value of
`I:"Total Loot Value to Create a New Bag"` as well.
