### ISSUE TITLE
Help please

### ISSUE THREAD

**Issue by MasterSloth1** [Malorolam/LootBags#127]
im probably derping somewhere along the lines but i cant figure this out for the life of me. im trying to create custom lootbags using the whitelist command in the config, but when i run lootbags_reloadconfig i get an error,
![b](https://user-images.githubusercontent.com/34207969/39963872-9b026898-56cb-11e8-98cd-adcda2f86f4b.PNG)

My code is 
[Lootbags_BagConfig.txt](https://github.com/Malorolam/LootBags/files/1998105/Lootbags_BagConfig.txt)

**Comment by MasterSloth1** [comment]
how did i miss that 🤦‍♂️ sorry for wasting your time

**Comment by MasterSloth1** [comment]
so if i understand this correctly i have to create a resource pack in order to get the default loot bag textures? all i want is your texture but change the colour to a different one but keep the default texture

**Comment by Malorolam** [comment]
You can use the $BAGCOLOR command to use the default texture with a custom colour applied.  The wiki entry is included for clarity.  

$BAGCOLOR:<main color>:<secondary color> - This command will set the bag texture to a default two-toned bag instead of a pre-defined one, colorizing the body to the main color and the neck to the secondary color. This has the benefit of bag customization without the need of resource pack creation. The colors are RGB colors separated by vertical bars (R|G|B). The default Worn Out bag shows an example of this command.

**Comment by MasterSloth1** [comment]
thats what i thought but when i load reload the config the textures are not there
![b](https://user-images.githubusercontent.com/34207969/39973861-87eb3b88-5778-11e8-9ea5-11fc91250419.PNG)

**Comment by MasterSloth1** [comment]
omg i just realised i have $BAGTEXTCOLOR:$WHITE not $BAGCOLOR

**Comment by MasterSloth1** [comment]
also while your here can you please elaborate on how to convert nbt to bytes i want to add tinkers patterns to a loot bag but im just confused lol thank you in advanced

**Comment by Malorolam** [comment]
the lootbags_helditemdump will give you the whitelist entry for whatever you're currently holding including the NBT data.

**Comment by MasterSloth1** [comment]
thanks very much for your help 😃
