### ISSUE TITLE
Question about weighting.

### ISSUE THREAD

**Issue by FuuNoKamiOka** [Malorolam/LootBags#14]
I wasn't sure where to put this since, but I had a question about weighting. I've added things to my whitelist and I'm not sure it worked properly.

As you can see from the list below, it's a mix of things. I've applied "50" to all because I have no idea what things need. I used to have "3" for the platinum items and they appeared sometimes, but not often. I changed it to 50 thinking it might be more frequent...it wasn't. Right now, the only things that show up from the list are the Ender IO Capacitor Bank and Thermal Expansion Capacitor. Nothing else is appearing.

Is there anyway you can make it easier to figure out the weight for each item? It's really confusing and I'd like to use the mod more, but the problem with weighting is frustrating me. :/

> "whitelisted items" {
    # Adding a modid and internal item name to this list will add the item to the Loot Bag drop table.  The entry must be in the form <modid>:<itemname>:<damage>:<min stack size>:<max stack size>:<weighting>:[<nbt data (seriously don't try to make this by hand)> (optional)]  Example to whitelist up to 16 iron ingots with a weight of 50: minecraft:iron_ingot:0:1:16:50.
    S:"Global Whitelist" <
        minecraft:golden_pickaxe:0:1:1:50
        minecraft:golden_sword:0:1:1:50
        minecraft:golden_shovel:0:1:1:50
        minecraft:golden_axe:0:1:1:50
	EnderIO:blockCapBank:3:1:1:50
        thermalexpansion:Frame:5:1:16:50
	ThermalExpansion:capacitor:5:1:1:50
        thermalfoundation:tool.swordPlatinum:0:1:1:50
        thermalfoundation:tool.pickaxePlatinum:0:1:1:50
        thermalfoundation:tool.shovelPlatinum:0:1:1:50
        thermalfoundation:tool.hoePlatinum:0:1:1:50
        thermalfoundation:tool.swordLead:0:1:1:50
        thermalfoundation:tool.pickaxeLead:0:1:1:50
        thermalfoundation:tool.shovelLead:0:1:1:50
        thermalfoundation:tool.hoeLead:0:1:1:50
        thermalfoundation:tool.swordTin:0:1:1:50
        thermalfoundation:tool.pickaxeTin:0:1:1:50
        thermalfoundation:tool.shovelTin:0:1:1:50
        thermalfoundation:tool.hoeTin:0:1:1:50
        thermalfoundation:tool.swordCopper:0:1:1:50
        thermalfoundation:tool.pickaxeCopper:0:1:1:50
        thermalfoundation:tool.shovelCopper:0:1:1:50
        thermalfoundation:tool.hoeCopper:0:1:1:50
        thermalfoundation:tool.swordSilver:0:1:1:50
        thermalfoundation:tool.pickaxeSilver:0:1:1:50
        thermalfoundation:tool.shovelSilver:0:1:1:50
        thermalfoundation:tool.hoeSilver:0:1:1:50
        thermalfoundation:tool.swordNickel:0:1:1:50
        thermalfoundation:tool.pickaxeNickel:0:1:1:50
        thermalfoundation:tool.shovelNickel:0:1:1:50
        thermalfoundation:tool.hoeNickel:0:1:1:50

**Comment by Malorolam** [comment]
The larger the weight, the more common an item shows up on average.  Since you made everything 50, in common bags the only thing you're going to get is those items most of the time.  I'm not sure why the thermal foundation tools aren't showing up.  The command lootbags_itemdump will create a file you can use to see everything in every lootbags table 
How the system works is that items have weight and every weight in the loot table is summed together.  Which when an item is determined, a random value up to that total weight is determined, the loot table is randomly sorted and it passes through the list, subtracting that item's weight from the random weight until the weight is 0 or less, in which that item is selected.

**Comment by FuuNoKamiOka** [comment]
I made a paste bag from the dump and the other TF tools don't show up at all. Did I do something wrong?
http://pastebin.com/ze5m8vmy

Also, that explanation nearly gave me a headache. lol Any way you could explain it so someone who doesn't know about the coding system can understand?

I Also want to point out that, with the way you describe your system it doesn't make sense to me. Right now I have a chest with 67 common, 42 uncommon and 4 rare Thaumcraft loot bags. I have no idea how many bags I've opened, but since I only have 25 Icosahedrans from Chance Cubes and the weight number for the Icosahedran is higher than all of the loot bags, how am I getting more of the loot bags and less of the Icsahedrans?

**Comment by Malorolam** [comment]
For the TF tools: Try uppercasing the T and F in ThermalFoundation, same for the ThermalExpansion frame.  In NEI's dumps that's how they are, and the modid lookup in Forge is case sensitive it seems.

The loot table system is rather odd, I used this system so that adding more items would be easy for users without having to dive into how the table is constructed and determined.  All the user has to deal with is the item definition and the weight.  Also, the mod is so RNG-heavy, it's extremely difficult to see how the weights affect how often items show up.

**Comment by FuuNoKamiOka** [comment]
I have changed the TF names and I will let you know if it works when I play again.

As far as the system, is there a ranger per bag? Say 41-50 is common, 31-40 is uncommon, 21-30 is rare, 11-20 is Epic, and 1-10 is Legendary? I doubt that's right, but it would give a base idea for users where to put certain items.

**Comment by Malorolam** [comment]
The weight ranges are defined in the bag config for each bag.  The default values are Common:1-unbounded, Uncommon:1-20, Rare:1-15, Epic:1-10, Legendary:1-5

**Comment by FuuNoKamiOka** [comment]
Okay. I think I understand the mod a bit more. Thanks for answering all my questions. lol I'm new to the mod and I'm trying to play in a world where I try to get everything from the bags. I think it's an interesting way to play and it's working so far. Thank you for your cooperation. :)
