### ISSUE TITLE
Quick Question...

### ISSUE THREAD

**Issue by Shade-Jonezy** [Malorolam/LootBags#148]
Is there any way you can post an example of NBT Data being used to define a specific item that shares the same Meta Data?

**Comment by Malorolam** [comment]
Dunno how I missed this, but I don't know what you mean. NBT is a data structure in the code, so it can vary depending on the mod, that is why I encode it to a byte array instead of trying to reproduce the structure. Trying to reproduce it by hand if you're not familiar with it can cause a lot of problems.
