### ISSUE TITLE
Bugged lootbags

### ISSUE THREAD

**Issue by C0rn3j** [Malorolam/LootBags#26]
When opening a bag, this has a high chance of happening.

http://pastebin.com/grjU5B9G

Forge 2092

LootBags-1.10.2-2.1.1.jar

This is the download for my private modpack I'm using, if you want to debug it yourself.

https://www.dropbox.com/sh/g4ig35lzo53zgv1/AADd8iGv5PujFc1dSrpOBGd0a?dl=1

**Comment by Malorolam** [comment]
No config file changes?

**Comment by C0rn3j** [comment]
Didn't touch em. Might be outdated .cfg from an older version though, but I didn't touch that either.

**Comment by Malorolam** [comment]
The issue is caused by something corrupting the vanilla loot tables which is bleeding into my tables.  I disabled IE and every bag except for common is working so I think issue 1449 might have something to do with it on their end, but something else is messing up too so I'll work on a way to at least identify what item is misbehaving and salvage as many items as possible.

**Comment by Malorolam** [comment]
Found the issue, [13:06:29] [Server thread/INFO] [FML]: [LOOTBAGS]: 1xitem.eplus.scroll@0:1:1:2147483647 is causing an integer overflow, making the table have a negative total weight, making it seem as though it's erroring.  Next version will ensure that similar issues cannot occur anymore.

**Comment by C0rn3j** [comment]
Maybe make an issue here then

https://github.com/Darkhax-Minecraft/Enchanting-Plus/issues
