### ISSUE TITLE
When i open lootbag it dissappears..

### ISSUE THREAD

**Issue by MigplaysMC** [Malorolam/LootBags#38]
so I was intrested in SkyFactory at this point and i downloaded and installed the mods. LootBag was there. and i said. "oh cool loot bags" but theres one problem..

everytime i open a loot bag it disappears :(
pls halp i need lootbags. loootbags are luv loot bags are lyfe

**Comment by Malorolam** [comment]
That typically means there are no items in the loot tables, usually because all the default sources are disabled or emptied by another mod, and there's no whitelisted items added.
If you downloaded the pack from Curse as the entire pack, it sounds like there was a glitch and my configs (and probably other files) got corrupted.  Delete the entire pack and try again, sometimes there's glitches like that.  
If you're trying to duplicate SF3, I can't help much, I don't have the configs.  You can try getting in contact with Darkosto to see if he'll give you them, but since there's a Let's Play of it going on, I'd expect there to be a release within a month.

**Comment by MigplaysMC** [comment]
Ok thanks, working on it.
