### ISSUE TITLE
Blacklist for Loottable is not working

### ISSUE THREAD

**Issue by ManuXzUWM** [Malorolam/LootBags#51]
Hello,

my problem is that I have tried to add the Enchanting Scrolls from "Enchanting Plus" mod to the loottable.
My options was:
`    S:"Global Blacklist" <
        eplus:scroll
     >`

And I have tried it with the ID `6389`, also with `eplus:scroll:0`.

The cfg file is not crashing and the Enchanting Scrolls are still in the loottable of the LootBags.

Best Regards
ManuXz
-Unitedworldmienrs Team-

**Comment by Malorolam** [comment]
I tested this and the global blacklist works just fine.
Make sure that you are putting each blacklist entry on a new line, otherwise it won't work.  Also the blacklist syntax is `<mod ID>:<item name>:<metadata>` to blacklist a specific item or '<mod ID>' to blacklist the entire mod.  Any other variation is invalid.

**Comment by ManuXzUWM** [comment]
Alright, thanks for this fast answer.
I will try it and report again if I can't handle it.
