### ISSUE TITLE
Black List per bag / White list per bag / Global Black List do not work

### ISSUE THREAD

**Issue by Dominance** [Malorolam/LootBags#6]
As the title states your black/white listing system is not functional with the latest version. Here is my config file. http://pastebin.com/pd9w2YG2 For example botania books still generate and they are on the global black list. Some of the custom items I added are not white listed in the bags listed. They are also no black listed on the bags choosen.

**Comment by Malorolam** [comment]
Your whitelisted items aren't working because you are missing the maximum stack size and weighting in the bag specific whitelists.  The botania book is also missing it's damage value in the blacklist.  Finally, a few of the blacklist entries have two spaces instead of one between fields, which shouldn't cause any problems, but I've never actually tested it.  That should fix most of the problems you are having.
In my code, whitelists are overridden by blacklists, so I'll take a look at it to try and find why bag-specific blacklisting isn't working.

**Comment by Dominance** [comment]
So your saying under for instance the legendary white list I need to also give it a stack size and weight?
Such as S:"Legendary Bag Whitelist" <
        beyondrealitycore item1 0 1 40 >

**Comment by Dominance** [comment]
and if that is so would I remove them from the global white list and put them in according to each bag?

**Comment by Dominance** [comment]
Ok I have attempted to add 
S:"Rare Bag Whitelist" <
        beyondrealitycore item10 0 1 30 

I have done this with that item removed from the global whitelist and added. Both ways with a item weight of 30. I dumped 100 bags into a chest 0 beyondrealitycore item10

**Comment by Dominance** [comment]
Got it figured out sorry for the spam :)

**Comment by Malorolam** [comment]
a weight of 30 is most likely too large for the rare bag, use the lootbagsitemdump command in game to see what maximum weight each bag is looking for and then use something less than that.  I plan on fixing that whole system so it's not as awkward to use.

**Comment by Dominance** [comment]
Yeah I did not notice that part on the mod page sorry about that. Seems as if the weight is under the bags weight it all works out.
