### ISSUE TITLE
Crashes when it loads

### ISSUE THREAD

**Issue by GrassMaster** [Malorolam/LootBags#66]

**Comment by GrassMaster** [comment]
https://gist.github.com/anonymous/752b0dfbb165833164002112a1c7a0f5

**Comment by Malorolam** [comment]
You are clearly using a modified version of the mod (UCHIE lootbags{2.0.16} [Loot Bags] (LootBags-Mod-1.7.10 (1).jar) ), use a version obtained from Curse and try again.

**Comment by GrassMaster** [comment]
i just got the curse one and it still crashes ill link you the site in case it is a fake https://mods.curse.com/mc-mods/minecraft/225946-lootbags/2356424

**Comment by Malorolam** [comment]
Update Forge to 10.13.4.1614, see if it still happens.

**Comment by GrassMaster** [comment]
i use minecraft 1.7.10 for mods

**Comment by Malorolam** [comment]
Yes, that's the last forge version for 1.7.10, there were some things changed between 1517 and 1614, possibly what is missing is one of those things.

**Comment by GrassMaster** [comment]
ok but how do i update it without screwing things up?

**Comment by Malorolam** [comment]
I don't know how you're setting up your modded instance, I'm guessing not the Twitch launcher since you're manually downloading mods.

**Comment by GrassMaster** [comment]
what is the diference of manually and not do you mean like skydaz?

**Comment by Malorolam** [comment]
A lot of people use the Twitch launcher (formerly the Curse launcher) for modded Minecraft nowadays since it simplifies a lot of the process, since you had a differently-named mod file and linked me the direct download link, you're downloading each mod manually from the site and putting them into the mods folder yourself.  

If you're using just the normal Minecraft launcher, installing a new version of forge just like you did the first time around will make a new version listed in the Version drop-down under the launch options for your instance.  Change the version to the 1614 one and it'll use that version of forge.

**Comment by GrassMaster** [comment]
ill try

**Comment by GrassMaster** [comment]
it still crashes should i try a skydaz installer??

**Comment by Malorolam** [comment]
I threw together your pack as best I could from the file names real quick and it loaded just fine for me, so I'm not sure what's going wrong.  Either there's something on your end that's messed up, which I can't help with, or one of the mods not on Curse I didn't get is causing a separate issue that is manifesting as a crash on my end.  I'll need a new crash log with the fixed mod version and updated forge to be able to help more.

**Comment by GrassMaster** [comment]
can you send me a download to the pack i use so i can test it grassmaster607@gmail.com

**Comment by GrassMaster** [comment]
i got it to work by useing the oldest possible version of it

**Comment by Malorolam** [comment]
Then it's definitely an issue with how your instance is set up and what forge version is being used.

**Comment by GrassMaster** [comment]
and i must say good job on the drops there legendary level
