### ISSUE TITLE
Server Thread/Info Message

### ISSUE THREAD

**Issue by Drenslace** [Malorolam/LootBags#74]
Hey thanks for the great mod! Anyways I am having one message that pops up a lot. I am trying to resolve it. I am using the Craft of the Titans modpack running 1.10.2 and this message comes up a lot.

[Server] Server thread/INFO [FML]: [LOOTBAGS]: Found entity of class: EntityLightMage['Light Mage'/1810444, l='world', x=526.12, y=10.59, z=-2.50]; This is probably an error somewhere so going to assume this is a monster.

I didn't know if there was a way i could correct this. I know this isn't entirely just the lootbags involved here but i didn't know if there was an entity list or something its trying to reference.

Thanks in advance!

**Comment by Malorolam** [comment]
It's ultimately an issue with the mod that's adding the light mage, that entity is not a sub-class of IMob, IAnimals, or EntityPlayer but it's capable of dropping items when it dies so I have to guess what it's supposed to be.  Most of the time, it's supposed to be a hostile mob so that's what I go with.
You can get rid of the message (and probably a few others) by setting Verbose Mode in the lootbags.cfg file to false, the issue is still there but the mod won't report it anymore.

**Comment by Drenslace** [comment]
Awesome thanks for the fast response! Muting the issue is good enough for me!
