### ISSUE TITLE
[suggestion]Make lootbags stackable

### ISSUE THREAD

**Issue by fluid-uu-matter** [Malorolam/LootBags#76]
In survival mode, every time I go out for hunting, my inventory is filled with the unstackable lootbags. I tried to use the stacksize mod to make it stackable, but it made lootbags to work buggy. So I want the lootbags to be stackable and work correctly when stacked.
I use MC1.10.2 but I want you update for all Minecraft versions.

**Comment by Malorolam** [comment]
The bags use NBT data for their inventory, which is attached to the ItemStack, as is the number of items in the stack.  If I were to make the bags stackable, I would introduce multiple new bugs and dupe glitches (which I've pretty much removed at this point) related to having that data interact and overwrite that I would then spend fixing instead of creating new content.  I don't consider this a valuable use of my time for a relatively minor feature.

**Comment by fluid-uu-matter** [comment]
Make unopened bags stackable and stacked bags unpoenable is a possible way.

**Comment by TheDeviantCrafter** [comment]
I know this is closed, but I have a potential solution. When a stack of unopened loot bags is right clicked, the opened loot bag would be added to a separate item stack. This could work like filling bottles with water, where it would add them to your inventory or drop them on the ground if there's no room.
