### ISSUE TITLE
Cant open loot bags

### ISSUE THREAD

**Issue by Killaheala** [Malorolam/LootBags#80]
I right click on them, shift right click, left click, pressed Q, i tried everything, cant open a bag

minecraft version 1.11.2

**Comment by Malorolam** [comment]
What other mods are you using?  Also post the two config files here.

**Comment by Killaheala** [comment]
Im using, buildcraft, journeymap, tinkers, biomes oplenty, pam harvestcraft, thermal expansion, lycanites, mystical agriculture, optifine, bibliocraft, caverns, chance cubes, decocraft, extra planets, inventory tweak, iron chest, JEI, roguelikedungeons, ruins, storage drawers, tree chopper, and waila, which config files?

**Comment by Malorolam** [comment]
The two lootbags config files, lootbags.cfg and Lootbags_Bag_Config.cfg.

**Comment by Killaheala** [comment]
http://pastebin.ca/3850961

http://pastebin.ca/3850963

**Comment by Malorolam** [comment]
The configs looks fine to me and I tested the mod setup except for optifine and everything opened fine.  Make a new instance with just Lootbags and see if the issue still occurs.

**Comment by Killaheala** [comment]
i did what you said and it seems like it doesnt work with buildcraft, something happen i dont know anything about computing thats why i dont even move something in the configs, any other idea?

**Comment by Malorolam** [comment]
I just pulled the recommended version off of Curse for Buildcraft, 7.99.6, there may have been a bug on their end that got fixed, or one that showed up if you're using a newer build.

**Comment by Iteries** [comment]
sorry to butt in... at first I had troubles opening the bags then I realized it was because I was looking down or at a wall but if you look at an open space before you about 5+ blocks away to the nearest wall/floor they open.  I know it's odd but you have to have nothing before you when opening a bag.  I find it an odd quirk but hey them bags are big on loot!  Much add fun and satisfaction when hunting about to get more than just xp or super rare drop item.    
So just right click when not facing a floor or a nearby wall surface.  They should open just fine.
