### ISSUE TITLE
Lootbags_BagConfig Wrong

### ISSUE THREAD

**Issue by IdenPropovad** [Malorolam/LootBags#86]
Whenever I attempt to launch Minecraft, it errors and says line 8 ( the crafted from part) is incorrect. $NULL does not work for some reason. Not sure why this is,  but I am using other mods in conjunction.
[crash-2017-08-21_09.29.27-client.txt](https://github.com/Malorolam/LootBags/files/1239515/crash-2017-08-21_09.29.27-client.txt)

[Lootbags_BagConfig.txt](https://github.com/Malorolam/LootBags/files/1239525/Lootbags_BagConfig.txt)

**Comment by Malorolam** [comment]
You still need a number, you probably have $CRAFTEDFROM:$NULL and you need $CRAFTEDFROM:$NULL:0.

**Comment by IdenPropovad** [comment]
Alright thanks. It appears that that is the issue with all the lootbags, is that intentional or did something go wrong somewhere along the  line?

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by Malorolam** [comment]
It sounds like something went wrong, if you had that config from a few versions ago, it's likely that the errors have always been there, but since I didn't make the game crash from them before they went unnoticed.  Which is precisely why I made the game crash from bag config errors now.  It'll probably take a few iterations, but by the errors give which line in the config and why it doesn't like it, so that and using the tutorial pages for reference and you'll be able to fix everything.

**Comment by IdenPropovad** [comment]
Thank you very much. By the way, I love this mod and all the rng goodness is brings, so thank you sooo much.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10
