### ISSUE TITLE
Whitelist parsing assumes too much about record names

### ISSUE THREAD

**Issue by tterrag1098** [Malorolam/LootBags#9]
My mod, customthings, allows pack makers to add records to the game. Your special code for ItemRecord (which I'm not even sure of the purpose of) breaks if the record does not start with "record.". You could fix this probably by doing `.replace("record.", "records.")`. But really I don't get why the code has to be there at all.

**Comment by tterrag1098** [comment]
Ok, the issue is much worse than I initially thought. Because of your code it is impossible to add my custom records to the whitelist PERIOD.

**Comment by Malorolam** [comment]
Aye, it's a terrible hacky method because a few forge versions ago records were being stored in a odd list type structure that didn't reflect in the item registry.  It's appeared to be changed now and the records are correctly named, making that code not needed anymore.  The current version is still rather rigid, it doesn't play nice with mods that add custom items which is something I'm working on.

**Comment by tterrag1098** [comment]
A fix would be appreciated, as @SirWyld was looking to get lootbags giving custom records in SF 2.5. My suggested fix should work as a temporary one.

**Comment by Malorolam** [comment]
Resolved in version 2.0.  I checked this in the dev environment and the custom items (at least the basic and record items) work with the whitelists.
